# Generated by Django 4.2.15 on 2024-10-13 15:13

import carros.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=9, verbose_name='Placa do carro')),
                ('marca', models.CharField(max_length=140, verbose_name='Marca do carro')),
                ('modelo', models.CharField(max_length=140, verbose_name='Modelo do carro')),
                ('ano', models.IntegerField(verbose_name='Ano do carro')),
                ('cor', models.CharField(max_length=140, verbose_name='Cor do carro')),
                ('quilometragem', models.IntegerField(verbose_name='Quilometragem do carro')),
                ('valor_diario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da diária')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=carros.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 400}}, verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='AluguelCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_dias', models.IntegerField(default=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
